### ISSUE TITLE
Condition is only met when C==P

### ISSUE THREAD

**Issue by danielspeixoto** [MaximeCheramy/simso#14]
https://github.com/MaximeCheramy/simso/blob/fd1d5f10aeeb8853674e2de19f59d508aa1429bf/simso/generator/task_generator.py#L139

Division of c/p is rounded to 0 whenever C!==P

**Comment by MaximeCheramy** [comment]
Indeed, I didn't notice this bug because it only happens in Python 2. Fixed in 63dab2a
