### ISSUE TITLE
umin constraint satisfaction not guaranteed

### ISSUE THREAD

**Issue by jeanibarz** [MaximeCheramy/simso#18]
https://github.com/MaximeCheramy/simso/blob/63dab2a5e9ac8e80d5dfb57b34bc6af7aa7ce80b/simso/generator/task_generator.py#L203

In some cases, umin constraint could be unsatisfied. I suggest to add :

`                if u < umin:
                    raise RuntimeWarning(
                        'Minimal task utilization constraint umin>=%d unsatisfied for one task'.format({umin}))`

To raise an exception informing whoever needs it that the constraint has been violated, but this would need to handle it...

A less intrusive workaround would be to add a comment in the function (in the documentation) to inform people about this behavior.

Best regards,
Jean Ibarz

**Comment by MaximeCheramy** [comment]
That's true, the utilization of the last task to be generated could violate the umin constraint.

The author of the algorithm wrote ("Portioned EDF-based scheduling on multiprocessors"):

> A task set Γ is generated as follows. A new periodic task is
> appended to Γ as long as U(Γ) ≤ Utot is satisfied. For each
> task τi, its utilization Ui is computed based on a uniform
> distribution within the range of [Umin, Umax]. **Only the utilization
> of the task generated at the very end is adjusted so
> that U(Γ) becomes equal to Utot.**

I think we could add this quote in a comment.

**Comment by jeanibarz** [comment]
Yes, this quote is relevant but tells implicitly the fact that a task might not satisfy the Umin constraint : I would add after the quote something like : "thus the Umin constraint might not be satisfied for the last task", just to explicitly inform users what's really going on without having to mind about this quote ;-)
