### ISSUE TITLE
Install instructions don't work.  

### ISSUE THREAD

**Issue by zipzit** [MaximeCheramy/simso#5]
I'm following the documentation instructions on this depository but they simply don't work.  The instructions clearly state type “python setup.py install” to install SimSo. Those instructions are a TOTAL FAIL. There is no setup.py file anywhere in any of those directories... (or am I'm just doing it wrong?)

Any hints on how to go from files stored in directories to compilation and execution?  Is there a suggested addendum to /docs/introduction.rst in this repository to something accurate and functional?

Many thanks,  Zip.

Note: I'm working in Ubuntu Desktop and the key directories (Simso, SimsoGui, SimPy, numpy and PyQt4) located at `.local/lib/python2.7/site-packages`

**Comment by MaximeCheramy** [comment]
I don't know what you're doing exactly, please give me the error messages. The setup file is here: https://github.com/MaximeCheramy/simso/blob/master/setup.py at the root of the project.
