### ISSUE TITLE
Cache partitioning

### ISSUE THREAD

**Issue by saadziasheikh** [MaximeCheramy/simso#6]
Hey,
Greater simulator. I was wondering if there is a cache partitioning feature where the cache can be partitioned across tasks or cores during execution to reduce interference. If not, is it possible to add scripts to enable such cache partitioning. Thanks!
Saad

**Comment by MaximeCheramy** [comment]
There are no cache partitioning feature in because with cache partitioning it's often possible to compute another WCET for the tasks.
However SimSo was designed with the objective to be as flexible as possible. You can implement your own model easily as a "Execution Time Model".

**Comment by saadziasheikh** [comment]
Hi,
okay. Thanks!
Saad
