### ISSUE TITLE
How to execute the available schedulers 

### ISSUE THREAD

**Issue by dbaltieri** [MaximeCheramy/simso#7]
Hello Cheramy,

I'm a computer science student and for now, I'm using macOS to write python codes. I'm already installed both SimSo, but I would like to know, how to execute one of the available schedulers after that. In fact, I have no idea how to execute SimSo. It was installed using the following command: pip install simso simsogui. 

Thanks !

**Comment by MaximeCheramy** [comment]
You can try to type "import simsogui" in a Python interpreter to start the graphical interface.

**Comment by fshahinfar1** [comment]
try this :
```
import simsogui
simsogui.run_gui()
```

**Comment by dbaltieri** [comment]
Thanks guys, it worked perfectly !

**Comment by dbaltieri** [comment]
Hello everyone, today I'm trying to do a simulation using sims,  I have a SIMSET and I would like to schedule it without using a GUI version, how can I do ?

**Comment by fshahinfar1** [comment]
Just follow the documents of simso.
http://projects.laas.fr/simso/doc/text_mode.html
